### ISSUE TITLE
Rename `init_phasespace` and `final_phasespace`

### ISSUE THREAD

**Issue by szabo137** [QEDjl-project/QEDprocesses.jl#15]
## Description of the problem

As discussed [here](https://github.com/QEDjl-project/QEDprocesses.jl/pull/14#discussion_r1337733988), the naming of `init_phasespace` and `final_phasespace` are somewhat misleading. The `init_` part suggests, that something is initialized, or that the phase-space somewhat changes. Both make technically and physically no sense. Similar for the `final_something`.

## Suggested solution
I suggest renaming all appearing instances: 

```
init_phasespace => in_phasespace
final_phasespace => out_phasespace
```

**Comment by Mithilesh-create** [comment]
Hello I would like to contribute , can you assign this to me.
