### ISSUE TITLE
Support minimal Julia version

### ISSUE THREAD

**Issue by szabo137** [QEDjl-project/QEDprocesses.jl#24]
We should be compatiple with the minimal Julia version which is tested in the ci, therefore `julia=1.6`.

See: 
https://github.com/QEDjl-project/QEDprocesses.jl/blob/84cbe112db9c4977a142681c12e429970b99f06d/Project.toml#L11

**Comment by SimeonEhrig** [comment]
This is automatically done with PR #21 
Otherwise all tests with Julia <1.9 would be fail.
