### ISSUE TITLE
Enhancement of phase space point

### ISSUE THREAD

**Issue by szabo137** [QEDjl-project/QEDprocesses.jl#58]
The current implementation of `ParticleStateful` and `PhaseSpacePoint` could be improved. Here we collect some ideas: 

## particle stateful
- [x] expose the types of the fields as type-parameters
- [x] remove spin information from particle stateful (will be added to the process interface)

## phase space point

- [x] Think about saving only the momenta and wrapping the particle stateful type only on access,
- [x] make `generate_phase_space` private and all it in a constructor of `PhaseSpacePoint`,
- [x] add construction of phase space points from coordinates, maybe using the functions `_generate_incoming_momenta` and `_generate_outgoing_momenta` from the process interface.  
- [x] add abbreviations for `momentum.(psp.in_particles)` and `momentum.(psp.out_particles`

**Comment by AntonReinhard** [comment]
Fully solved with #63 and #68
