### ISSUE TITLE
Double exports

### ISSUE THREAD

**Issue by szabo137** [QEDjl-project/QEDprocesses.jl#73]
Some exports are there two times... blaming myself for merging stuff incorrectly.

https://github.com/QEDjl-project/QEDprocesses.jl/blob/c768a574850d3135a9d5a5572e6881e3250b20a8/src/QEDprocesses.jl#L16C1-L21C25

**Comment by AntonReinhard** [comment]
Has been resolved somewhere in the refactoring.
